---
- name: Add Docker GPG key for Ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker GPG key for CentOS
  rpm_key:
    key: "https://download.docker.com/linux/centos/gpg"
    state: present
  when: ansible_distribution == 'CentOS'

- name: Add Docker YUM repository
  yum_repository:
    name: docker-ce
    description: Docker CE YUM repository
    baseurl: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/x86_64/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: true
    gpgcheck: true
  when: ansible_distribution == 'CentOS'

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce
    update_cache: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install Docker CE
  package:
    name: docker-ce
    state: present
  when: ansible_os_family == 'Debian' or ansible_distribution == 'CentOS'

- name: Restart Docker Service
  service:
    name: docker
    state: restarted
  notify: Restart Docker
