---
# Role name: docker
# Role for installing Docker on CentOS

- name: Ensure Docker dependencies are installed
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Set up the Docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    exclude: containerd.io
  notify: Restart Docker Service

- name: Install Docker
  package:
    name: docker-ce
    state: present

- name: Start and enable the Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker installation
  command: docker run hello-world

- name: Restart Docker Service
  service:
    name: docker
    state: restarted
