name: Test Centos

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ANSIBLE_VERSION: "2.9"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        os: [centos-7, centos-8, centos-9]
        ansible_version: [2.9, 2.8, 2.7]

    name: Test on ${{ matrix.os }} with Ansible ${{ matrix.ansible_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install ansible=={{ matrix.ansible_version }}

    - name: Run tests
      run: |
        ansible-galaxy install --roles-path=roles -r requirements.yml